### ISSUE TITLE
MMKV storage getting cleared after app background/killed — Urgent help Needed

### ISSUE THREAD

**Issue by rrohini-chaudharii** [mrousavy/react-native-mmkv#852]
Hi everyone,

We're currently facing a critical issue with MMKV in our React Native app that I need to look into urgently. Hoping to get some insights or suggestions from anyone who's encountered something similar.
I am using encrypted storage with MMKV.

📌 Issue Summary:

When the app is in use, MMKV behaves as expected — reads/writes work fine.

However, in certain cases, when the app is sent to the background or force closed and reopened after a while, the storage comes back empty, causing users to be logged out.

This isn't happening every time, but it’s occurring frequently enough to cause real problems for our users.

Most stored values are lightweight. 

We're using:

React Native: 0.81

react-native-mmkv: 3.3.0
This has been observed across multiple devices and OS versions, not isolated to any specific environment.

Has anyone else seen this behavior recently or found any reliable workarounds? I’m currently blocked on this and would appreciate any help — we're looking to resolve this ASAP.

Thanks in advance.

**Comment by rrohini-chaudharii** [comment]
@mrousavy I am getting this error message on iOS - [E] MiniPBCoder.cpp:591::decodeOneMap InvalidProtocolBuffer truncatedMessage

**Comment by mrousavy** [comment]
Being impatient will get you nowhere. We all have things to do.

I think this has been fixed in [react-native-mmkv 4.x.x-beta](https://github.com/mrousavy/react-native-mmkv/releases/tag/v4.0.0-beta.0).

**Comment by rrohini-chaudharii** [comment]
Hey @mrousavy, Understood and I appreciate your time. Thanks for pointing out the fix in react-native-mmkv 4.x.x-beta. 
I upgraded to 4.0.0-beta.1 version and checked, clear data issue still persists. Its not yet fixed in this release. 
Also with this release Android build is also failing with below error : 

Could not find a package configuration file provided by "mmkv" with any of
the following names:
  mmkvConfig.cmake
  mmkv-config.cmake

**Comment by ninad-joshi-asurion** [comment]
@mrousavy facing the same issue in IOS.. Data is getting wiped from MMKV.. getting this error

[E] <MiniPBCoder.cpp:591::decodeOneMap> InvalidProtocolBuffer truncatedMessage

I have tried the new beta version. It still doesn't work

**Comment by arakovskis** [comment]
Facing the same issue

**Comment by rrohini-chaudharii** [comment]
@mrousavy Any update on this issue? Still getting this issue multiple times..

**Comment by pratikSeven** [comment]
Hi @mrousavy,

Just confirming if release 3.3.1 fixes the issue described in this thread. We're seeing the same problem on our end.

Thanks!

**Comment by andrejsoucek** [comment]
Our users are being constantly logged out due to removed refresh token from the storage. @mrousavy can we reopen this?

**Comment by gituser8796** [comment]
@mrousavy could you please have a look? It looks like this issue is becoming more frequent with the latest iOS 26.x releases.

**Comment by gituser8796** [comment]
@rrohini-chaudharii were you able to find a solution for this one?

**Comment by rrohini-chaudharii** [comment]
@gituser8796 No I am still getting this issue..No solution found yet.

**Comment by gituser8796** [comment]
@rrohini-chaudharii this happens to us as well, but we don't have a way to reproduce it. Do you happen to know if 3.2.0 works well? We're trying to figure out what to do - any help would be appreciated!
