### ISSUE TITLE
Beta 8 not on NPM yet ?

### ISSUE THREAD

**Issue by leoboyerbx** [mrousavy/react-native-mmkv#878]
Hi, thanks for the awesome work in this lib!

It seems the latest beta (that fixes expo build) is not released on NPM. Maybe it's related to [the version not updated in the package.json](https://github.com/mrousavy/react-native-mmkv/blob/a6e0fbe85fd482fe723b9cbd8a142b98211fa759/packages/react-native-mmkv/package.json#L3) ?

**Comment by spyshower** [comment]
This happened for all version 4 betas, something is off.

**Comment by mrousavy** [comment]
> Beta 8 not on NPM yet ?

My bad - I had an issue where the actual npm version was just one number smaller than the GitHub version - even though it's the same code. So beta.8 on GitHub = beta.7 on npm.

But I just fixed it and released beta.8 on npm, without bumping the git number - now it's in sync again- thanks for the heads up! 👍 

> that fixes expo build

Please test that feature btw - I did not test that at all. The idea is that it removes the 32-bit architectures from `gradle.properties` - if you find a bug in it, I'd really appreciate any PRs that fix it.

> This happened for all version 4 betas, something is off.

That's not true. 

<img width="800" height="614" alt="Image" src="https://github.com/user-attachments/assets/1ce737b5-a3ef-4f5a-844b-899b39de4657" />

**Comment by spyshower** [comment]
@mrousavy I think I had noticed for all beta versions after v1 that the latest version available to download was always 1 less than what you had released.

Anyway it doesn't matter; thanks for your work buddy.

**Comment by leoboyerbx** [comment]
Hi @mrousavy Thanks for the super quick fix !

In the meantime, I had tried by making my own expo config plugin and it does not seem to work (still crash with architecture-related stuff)
I also had to make another config plugin to make the iOS Pod Install with expo pass.

But all of this is off-topic so I will open separate issues.

**Comment by mrousavy** [comment]
See [this discussion for beta build errors](https://github.com/react-native-community/nightly-tests/pull/21)

**Comment by leoboyerbx** [comment]
Yeah, saw the discussion. I've added an issue for the Android not building #881, but maybe it's not relevant here ?
At least I opened a PR that fixes the expo module, does not fix the build but at least Expo projects now have a correct `gradle.properties`: #880
